#application properties




# HTTP (Tomcat) port
server:
  port: 8502
  servlet: 
   context-path : /tracktrace
  ssl:
    key-store-type: PKCS12
    key-store: STAR_ias.p12
    key-store-password: password    
    key-alias: 1

#kafka server GCP and topic name    
kafka:
  bootstrap-servers: 10.3.0.3:9092,10.3.0.4:9092,10.3.0.6:9092  
  topic:
    shipmentException: VISIBILITY_SHIPMENTEXCEPTION_PROD
    shipmentEvents: VISIBILITY_SHIPMENTEVENT_PROD
    shipmentOceanEvents: VISIBILITY_OCEANSHIPMENTEVENT_PROD
    shipmentV2: VISIBILITY_SHIPMENT_PROD
    shipmentV1: VISIBILITY_WORKORDER_PROD
    tenderShipment: VISIBILITY_TENDERSHIPMENT_PROD
    genericShipment: VISIBILITY_SHIPMENT_PROD
  isException: false
   
#logging


logging:
   config: classpath:log4j2-prod.yaml
   level: 
     root: ERROR
     org.springframework.data: ERROR
     org.springframework.security: ERROR

#cxf
cxf:
  path: /
  servlet.init: 
    service-list-path: /info
  jaxrs: 
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics
    
 
spring:
  datasource:
    bmv:
      url: jdbc:oracle:thin:@iaspd01-02-scan.interasset.com:1521/iasprod
      username: BMV
      password: BMV155ss0ur132
      driverClass:  oracle.jdbc.driver.OracleDriver
# dbcp2 settings 
      dbcp2:
        initial-size: 5
        max-total: 25
        pool-prepared-statements: true
    dm:
      url: jdbc:oracle:thin:@iaspd01-02-scan.interasset.com:1521/iasprod
      username: DM
      password: M155ss0ur132
      driverClass:  oracle.jdbc.driver.OracleDriver

  jpa:
    properties:
      hibernate:
        show-sql:true
        use-sql-comments:true
        format-sql:true

client:
  hub:
    address: http://iashub.interasset.com/Hub6/hub-services/DispatchManagerFacadeService
  le:
    address: https://api.iasdispatchmanager.com:8503/v1/railbilling/
    railBillingUpdateAddress: https://api.iasdispatchmanager.com:8503/v1/railbilling/updateStatus/
  blockchain:
    baseUrl: https://dev-blockchain.blumeglobal.com:7777      
  wo:
    workOrderURL: https://test.iasdispatchmanager.com/dispatchmanager
    authenticationapiKey: clP8hFuKWZBteBGY1rZRBS1y86qTezY6
  locationMaster:
    locationMasterFindOrCreate: http://10.3.0.25:32600/api/v1/locations/findcreate
    locationMasterFindAddress: http://10.3.0.25:32600/api/v1/locations/findaddress
    locationMasterFindById: http://10.3.0.25:32600/api/v1/locations/{uuid}
    locationMasterFindByUnlocode: http://10.3.0.25:32600/api/v1/locations/unlocode/{unlocode}    